([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:abuse_of_authority \"true\" ) ) => ( art416_basic ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:abuse_of_authority \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_gain \"true\" ) ) => ( art416_qualified_gain ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art416_qualified_gain)
   (negated no)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule2_neg] of defeasible-rule
   (rule-name rule2_neg)
   (original-rule "rule2_neg ( declare ( superior rule1 ) ) ( art416_qualified_gain ( defendant ?Defendant ) ) => ( not ( art416_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated yes)
   (superior rule1)
   (deductive-rule rule2_neg-deductive)
   (overruled-rule rule2_neg-overruled)
   (system no)
   (support-rule rule2_neg-support)
   (defeasibly-rule rule2_neg-defeasibly)
   (defeated-rule rule2_neg-defeated))

([rule3] of defeasible-rule
   (rule-name rule3)
   (original-rule "rule3 ( lc:case ( lc:defendant ?Defendant ) ( lc:abuse_of_authority \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:organized_group \"true\" ) ) => ( art416_organized ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art416_organized)
   (negated no)
   (superior)
   (deductive-rule rule3-deductive)
   (overruled-rule rule3-overruled)
   (system no)
   (support-rule rule3-support)
   (defeasibly-rule rule3-defeasibly)
   (defeated-rule nil))

([rule3_neg1] of defeasible-rule
   (rule-name rule3_neg1)
   (original-rule "rule3_neg1 ( declare ( superior rule1 ) ) ( art416_organized ( defendant ?Defendant ) ) => ( not ( art416_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated yes)
   (superior rule1)
   (deductive-rule rule3_neg1-deductive)
   (overruled-rule rule3_neg1-overruled)
   (system no)
   (support-rule rule3_neg1-support)
   (defeasibly-rule rule3_neg1-defeasibly)
   (defeated-rule rule3_neg1-defeated))

([rule3_neg2] of defeasible-rule
   (rule-name rule3_neg2)
   (original-rule "rule3_neg2 ( declare ( superior rule2 ) ) ( art416_organized ( defendant ?Defendant ) ) => ( not ( art416_qualified_gain ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_qualified_gain)
   (negated yes)
   (superior rule2)
   (deductive-rule rule3_neg2-deductive)
   (overruled-rule rule3_neg2-overruled)
   (system no)
   (support-rule rule3_neg2-support)
   (defeasibly-rule rule3_neg2-defeasibly)
   (defeated-rule rule3_neg2-defeated))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( lc:case ( lc:defendant ?Defendant ) ( lc:embezzlement \"true\" ) ) => ( art420_basic ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art420_basic)
   (negated no)
   (superior)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule nil))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:embezzlement \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_gain \"true\" ) ) => ( art420_qualified ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art420_qualified)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule5_neg] of defeasible-rule
   (rule-name rule5_neg)
   (original-rule "rule5_neg ( declare ( superior rule4 ) ) ( art420_qualified ( defendant ?Defendant ) ) => ( not ( art420_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art420_basic)
   (negated yes)
   (superior rule4)
   (deductive-rule rule5_neg-deductive)
   (overruled-rule rule5_neg-overruled)
   (system no)
   (support-rule rule5_neg-support)
   (defeasibly-rule rule5_neg-defeasibly)
   (defeated-rule rule5_neg-defeated))

([rule4_neg_416b] of defeasible-rule
   (rule-name rule4_neg_416b)
   (original-rule "rule4_neg_416b ( declare ( superior rule1 ) ) ( art420_basic ( defendant ?Defendant ) ) => ( not ( art416_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated yes)
   (superior rule1)
   (deductive-rule rule4_neg_416b-deductive)
   (overruled-rule rule4_neg_416b-overruled)
   (system no)
   (support-rule rule4_neg_416b-support)
   (defeasibly-rule rule4_neg_416b-defeasibly)
   (defeated-rule rule4_neg_416b-defeated))

([rule4_neg_416qg] of defeasible-rule
   (rule-name rule4_neg_416qg)
   (original-rule "rule4_neg_416qg ( declare ( superior rule2 ) ) ( art420_basic ( defendant ?Defendant ) ) => ( not ( art416_qualified_gain ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_qualified_gain)
   (negated yes)
   (superior rule2)
   (deductive-rule rule4_neg_416qg-deductive)
   (overruled-rule rule4_neg_416qg-overruled)
   (system no)
   (support-rule rule4_neg_416qg-support)
   (defeasibly-rule rule4_neg_416qg-defeasibly)
   (defeated-rule rule4_neg_416qg-defeated))

([rule4_neg_416org] of defeasible-rule
   (rule-name rule4_neg_416org)
   (original-rule "rule4_neg_416org ( declare ( superior rule3 ) ) ( art420_basic ( defendant ?Defendant ) ) => ( not ( art416_organized ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_organized)
   (negated yes)
   (superior rule3)
   (deductive-rule rule4_neg_416org-deductive)
   (overruled-rule rule4_neg_416org-overruled)
   (system no)
   (support-rule rule4_neg_416org-support)
   (defeasibly-rule rule4_neg_416org-defeasibly)
   (defeated-rule rule4_neg_416org-defeated))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( lc:case ( lc:defendant ?Defendant ) ( lc:trading_influence \"true\" ) ) => ( art422_basic ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art422_basic)
   (negated no)
   (superior)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule nil))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( lc:case ( lc:defendant ?Defendant ) ( lc:trading_influence \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:organized_group \"true\" ) ) => ( art422_organized ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art422_organized)
   (negated no)
   (superior)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule nil))

([rule7_neg] of defeasible-rule
   (rule-name rule7_neg)
   (original-rule "rule7_neg ( declare ( superior rule6 ) ) ( art422_organized ( defendant ?Defendant ) ) => ( not ( art422_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art422_basic)
   (negated yes)
   (superior rule6)
   (deductive-rule rule7_neg-deductive)
   (overruled-rule rule7_neg-overruled)
   (system no)
   (support-rule rule7_neg-support)
   (defeasibly-rule rule7_neg-defeasibly)
   (defeated-rule rule7_neg-defeated))

([rule6_neg_416b] of defeasible-rule
   (rule-name rule6_neg_416b)
   (original-rule "rule6_neg_416b ( declare ( superior rule1 ) ) ( art422_basic ( defendant ?Defendant ) ) => ( not ( art416_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated yes)
   (superior rule1)
   (deductive-rule rule6_neg_416b-deductive)
   (overruled-rule rule6_neg_416b-overruled)
   (system no)
   (support-rule rule6_neg_416b-support)
   (defeasibly-rule rule6_neg_416b-defeasibly)
   (defeated-rule rule6_neg_416b-defeated))

([rule6_neg_416qg] of defeasible-rule
   (rule-name rule6_neg_416qg)
   (original-rule "rule6_neg_416qg ( declare ( superior rule2 ) ) ( art422_basic ( defendant ?Defendant ) ) => ( not ( art416_qualified_gain ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_qualified_gain)
   (negated yes)
   (superior rule2)
   (deductive-rule rule6_neg_416qg-deductive)
   (overruled-rule rule6_neg_416qg-overruled)
   (system no)
   (support-rule rule6_neg_416qg-support)
   (defeasibly-rule rule6_neg_416qg-defeasibly)
   (defeated-rule rule6_neg_416qg-defeated))

([rule6_neg_416org] of defeasible-rule
   (rule-name rule6_neg_416org)
   (original-rule "rule6_neg_416org ( declare ( superior rule3 ) ) ( art422_basic ( defendant ?Defendant ) ) => ( not ( art416_organized ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_organized)
   (negated yes)
   (superior rule3)
   (deductive-rule rule6_neg_416org-deductive)
   (overruled-rule rule6_neg_416org-overruled)
   (system no)
   (support-rule rule6_neg_416org-support)
   (defeasibly-rule rule6_neg_416org-defeasibly)
   (defeated-rule rule6_neg_416org-defeated))

([rule8] of defeasible-rule
   (rule-name rule8)
   (original-rule "rule8 ( lc:case ( lc:defendant ?Defendant ) ( lc:bribery_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:bribe_receiver \"true\" ) ) => ( art423_basic ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art423_basic)
   (negated no)
   (superior)
   (deductive-rule rule8-deductive)
   (overruled-rule rule8-overruled)
   (system no)
   (support-rule rule8-support)
   (defeasibly-rule rule8-defeasibly)
   (defeated-rule nil))

([rule9] of defeasible-rule
   (rule-name rule9)
   (original-rule "rule9 ( lc:case ( lc:defendant ?Defendant ) ( lc:bribery_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:bribe_receiver \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:high_bribery \"true\" ) ) => ( art423_qualified ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art423_qualified)
   (negated no)
   (superior)
   (deductive-rule rule9-deductive)
   (overruled-rule rule9-overruled)
   (system no)
   (support-rule rule9-support)
   (defeasibly-rule rule9-defeasibly)
   (defeated-rule nil))

([rule9_neg] of defeasible-rule
   (rule-name rule9_neg)
   (original-rule "rule9_neg ( declare ( superior rule8 ) ) ( art423_qualified ( defendant ?Defendant ) ) => ( not ( art423_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art423_basic)
   (negated yes)
   (superior rule8)
   (deductive-rule rule9_neg-deductive)
   (overruled-rule rule9_neg-overruled)
   (system no)
   (support-rule rule9_neg-support)
   (defeasibly-rule rule9_neg-defeasibly)
   (defeated-rule rule9_neg-defeated))

([rule8_neg_416b] of defeasible-rule
   (rule-name rule8_neg_416b)
   (original-rule "rule8_neg_416b ( declare ( superior rule1 ) ) ( art423_basic ( defendant ?Defendant ) ) => ( not ( art416_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated yes)
   (superior rule1)
   (deductive-rule rule8_neg_416b-deductive)
   (overruled-rule rule8_neg_416b-overruled)
   (system no)
   (support-rule rule8_neg_416b-support)
   (defeasibly-rule rule8_neg_416b-defeasibly)
   (defeated-rule rule8_neg_416b-defeated))

([rule8_neg_416qg] of defeasible-rule
   (rule-name rule8_neg_416qg)
   (original-rule "rule8_neg_416qg ( declare ( superior rule2 ) ) ( art423_basic ( defendant ?Defendant ) ) => ( not ( art416_qualified_gain ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_qualified_gain)
   (negated yes)
   (superior rule2)
   (deductive-rule rule8_neg_416qg-deductive)
   (overruled-rule rule8_neg_416qg-overruled)
   (system no)
   (support-rule rule8_neg_416qg-support)
   (defeasibly-rule rule8_neg_416qg-defeasibly)
   (defeated-rule rule8_neg_416qg-defeated))

([rule8_neg_416org] of defeasible-rule
   (rule-name rule8_neg_416org)
   (original-rule "rule8_neg_416org ( declare ( superior rule3 ) ) ( art423_basic ( defendant ?Defendant ) ) => ( not ( art416_organized ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_organized)
   (negated yes)
   (superior rule3)
   (deductive-rule rule8_neg_416org-deductive)
   (overruled-rule rule8_neg_416org-overruled)
   (system no)
   (support-rule rule8_neg_416org-support)
   (defeasibly-rule rule8_neg_416org-defeasibly)
   (defeated-rule rule8_neg_416org-defeated))

([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( lc:case ( lc:defendant ?Defendant ) ( lc:bribery_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:bribe_receiver \"false\" ) ) => ( art424_basic ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art424_basic)
   (negated no)
   (superior)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule nil))

([rule11] of defeasible-rule
   (rule-name rule11)
   (original-rule "rule11 ( lc:case ( lc:defendant ?Defendant ) ( lc:bribery_involved \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:bribe_receiver \"false\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:voluntary_disclosure \"true\" ) ) => ( art424_acquittal ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class art424_acquittal)
   (negated no)
   (superior)
   (deductive-rule rule11-deductive)
   (overruled-rule rule11-overruled)
   (system no)
   (support-rule rule11-support)
   (defeasibly-rule rule11-defeasibly)
   (defeated-rule nil))

([rule11_neg] of defeasible-rule
   (rule-name rule11_neg)
   (original-rule "rule11_neg ( declare ( superior rule10 ) ) ( art424_acquittal ( defendant ?Defendant ) ) => ( not ( art424_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art424_basic)
   (negated yes)
   (superior rule10)
   (deductive-rule rule11_neg-deductive)
   (overruled-rule rule11_neg-overruled)
   (system no)
   (support-rule rule11_neg-support)
   (defeasibly-rule rule11_neg-defeasibly)
   (defeated-rule rule11_neg-defeated))

([rule10_neg_416b] of defeasible-rule
   (rule-name rule10_neg_416b)
   (original-rule "rule10_neg_416b ( declare ( superior rule1 ) ) ( art424_basic ( defendant ?Defendant ) ) => ( not ( art416_basic ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_basic)
   (negated yes)
   (superior rule1)
   (deductive-rule rule10_neg_416b-deductive)
   (overruled-rule rule10_neg_416b-overruled)
   (system no)
   (support-rule rule10_neg_416b-support)
   (defeasibly-rule rule10_neg_416b-defeasibly)
   (defeated-rule rule10_neg_416b-defeated))

([rule10_neg_416qg] of defeasible-rule
   (rule-name rule10_neg_416qg)
   (original-rule "rule10_neg_416qg ( declare ( superior rule2 ) ) ( art424_basic ( defendant ?Defendant ) ) => ( not ( art416_qualified_gain ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_qualified_gain)
   (negated yes)
   (superior rule2)
   (deductive-rule rule10_neg_416qg-deductive)
   (overruled-rule rule10_neg_416qg-overruled)
   (system no)
   (support-rule rule10_neg_416qg-support)
   (defeasibly-rule rule10_neg_416qg-defeasibly)
   (defeated-rule rule10_neg_416qg-defeated))

([rule10_neg_416org] of defeasible-rule
   (rule-name rule10_neg_416org)
   (original-rule "rule10_neg_416org ( declare ( superior rule3 ) ) ( art424_basic ( defendant ?Defendant ) ) => ( not ( art416_organized ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class art416_organized)
   (negated yes)
   (superior rule3)
   (deductive-rule rule10_neg_416org-deductive)
   (overruled-rule rule10_neg_416org-overruled)
   (system no)
   (support-rule rule10_neg_416org-support)
   (defeasibly-rule rule10_neg_416org-defeasibly)
   (defeated-rule rule10_neg_416org-defeated))

([pen_416b_min] of defeasible-rule
   (rule-name pen_416b_min)
   (original-rule "pen_416b_min ( art416_basic ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_416b_min-deductive)
   (overruled-rule pen_416b_min-overruled)
   (system no)
   (support-rule pen_416b_min-support)
   (defeasibly-rule pen_416b_min-defeasibly)
   (defeated-rule nil))

([pen_416b_max] of defeasible-rule
   (rule-name pen_416b_max)
   (original-rule "pen_416b_max ( art416_basic ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_416b_max-deductive)
   (overruled-rule pen_416b_max-overruled)
   (system no)
   (support-rule pen_416b_max-support)
   (defeasibly-rule pen_416b_max-defeasibly)
   (defeated-rule nil))

([pen_416qg_min] of defeasible-rule
   (rule-name pen_416qg_min)
   (original-rule "pen_416qg_min ( art416_qualified_gain ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_416qg_min-deductive)
   (overruled-rule pen_416qg_min-overruled)
   (system no)
   (support-rule pen_416qg_min-support)
   (defeasibly-rule pen_416qg_min-defeasibly)
   (defeated-rule nil))

([pen_416qg_max] of defeasible-rule
   (rule-name pen_416qg_max)
   (original-rule "pen_416qg_max ( art416_qualified_gain ( defendant ?Defendant ) ) => ( max_imprisonment ( value 10 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_416qg_max-deductive)
   (overruled-rule pen_416qg_max-overruled)
   (system no)
   (support-rule pen_416qg_max-support)
   (defeasibly-rule pen_416qg_max-defeasibly)
   (defeated-rule nil))

([pen_416org_min] of defeasible-rule
   (rule-name pen_416org_min)
   (original-rule "pen_416org_min ( art416_organized ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_416org_min-deductive)
   (overruled-rule pen_416org_min-overruled)
   (system no)
   (support-rule pen_416org_min-support)
   (defeasibly-rule pen_416org_min-defeasibly)
   (defeated-rule nil))

([pen_416org_max] of defeasible-rule
   (rule-name pen_416org_max)
   (original-rule "pen_416org_max ( art416_organized ( defendant ?Defendant ) ) => ( max_imprisonment ( value 12 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_416org_max-deductive)
   (overruled-rule pen_416org_max-overruled)
   (system no)
   (support-rule pen_416org_max-support)
   (defeasibly-rule pen_416org_max-defeasibly)
   (defeated-rule nil))

([pen_420b_min] of defeasible-rule
   (rule-name pen_420b_min)
   (original-rule "pen_420b_min ( art420_basic ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_420b_min-deductive)
   (overruled-rule pen_420b_min-overruled)
   (system no)
   (support-rule pen_420b_min-support)
   (defeasibly-rule pen_420b_min-defeasibly)
   (defeated-rule nil))

([pen_420b_max] of defeasible-rule
   (rule-name pen_420b_max)
   (original-rule "pen_420b_max ( art420_basic ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_420b_max-deductive)
   (overruled-rule pen_420b_max-overruled)
   (system no)
   (support-rule pen_420b_max-support)
   (defeasibly-rule pen_420b_max-defeasibly)
   (defeated-rule nil))

([pen_420q_min] of defeasible-rule
   (rule-name pen_420q_min)
   (original-rule "pen_420q_min ( art420_qualified ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_420q_min-deductive)
   (overruled-rule pen_420q_min-overruled)
   (system no)
   (support-rule pen_420q_min-support)
   (defeasibly-rule pen_420q_min-defeasibly)
   (defeated-rule nil))

([pen_420q_max] of defeasible-rule
   (rule-name pen_420q_max)
   (original-rule "pen_420q_max ( art420_qualified ( defendant ?Defendant ) ) => ( max_imprisonment ( value 10 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_420q_max-deductive)
   (overruled-rule pen_420q_max-overruled)
   (system no)
   (support-rule pen_420q_max-support)
   (defeasibly-rule pen_420q_max-defeasibly)
   (defeated-rule nil))

([pen_422b_min] of defeasible-rule
   (rule-name pen_422b_min)
   (original-rule "pen_422b_min ( art422_basic ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_422b_min-deductive)
   (overruled-rule pen_422b_min-overruled)
   (system no)
   (support-rule pen_422b_min-support)
   (defeasibly-rule pen_422b_min-defeasibly)
   (defeated-rule nil))

([pen_422b_max] of defeasible-rule
   (rule-name pen_422b_max)
   (original-rule "pen_422b_max ( art422_basic ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_422b_max-deductive)
   (overruled-rule pen_422b_max-overruled)
   (system no)
   (support-rule pen_422b_max-support)
   (defeasibly-rule pen_422b_max-defeasibly)
   (defeated-rule nil))

([pen_422org_min] of defeasible-rule
   (rule-name pen_422org_min)
   (original-rule "pen_422org_min ( art422_organized ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_422org_min-deductive)
   (overruled-rule pen_422org_min-overruled)
   (system no)
   (support-rule pen_422org_min-support)
   (defeasibly-rule pen_422org_min-defeasibly)
   (defeated-rule nil))

([pen_422org_max] of defeasible-rule
   (rule-name pen_422org_max)
   (original-rule "pen_422org_max ( art422_organized ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_422org_max-deductive)
   (overruled-rule pen_422org_max-overruled)
   (system no)
   (support-rule pen_422org_max-support)
   (defeasibly-rule pen_422org_max-defeasibly)
   (defeated-rule nil))

([pen_423b_min] of defeasible-rule
   (rule-name pen_423b_min)
   (original-rule "pen_423b_min ( art423_basic ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_423b_min-deductive)
   (overruled-rule pen_423b_min-overruled)
   (system no)
   (support-rule pen_423b_min-support)
   (defeasibly-rule pen_423b_min-defeasibly)
   (defeated-rule nil))

([pen_423b_max] of defeasible-rule
   (rule-name pen_423b_max)
   (original-rule "pen_423b_max ( art423_basic ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_423b_max-deductive)
   (overruled-rule pen_423b_max-overruled)
   (system no)
   (support-rule pen_423b_max-support)
   (defeasibly-rule pen_423b_max-defeasibly)
   (defeated-rule nil))

([pen_423q_min] of defeasible-rule
   (rule-name pen_423q_min)
   (original-rule "pen_423q_min ( art423_qualified ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_423q_min-deductive)
   (overruled-rule pen_423q_min-overruled)
   (system no)
   (support-rule pen_423q_min-support)
   (defeasibly-rule pen_423q_min-defeasibly)
   (defeated-rule nil))

([pen_423q_max] of defeasible-rule
   (rule-name pen_423q_max)
   (original-rule "pen_423q_max ( art423_qualified ( defendant ?Defendant ) ) => ( max_imprisonment ( value 12 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_423q_max-deductive)
   (overruled-rule pen_423q_max-overruled)
   (system no)
   (support-rule pen_423q_max-support)
   (defeasibly-rule pen_423q_max-defeasibly)
   (defeated-rule nil))

([pen_424b_min] of defeasible-rule
   (rule-name pen_424b_min)
   (original-rule "pen_424b_min ( art424_basic ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_424b_min-deductive)
   (overruled-rule pen_424b_min-overruled)
   (system no)
   (support-rule pen_424b_min-support)
   (defeasibly-rule pen_424b_min-defeasibly)
   (defeated-rule nil))

([pen_424b_max] of defeasible-rule
   (rule-name pen_424b_max)
   (original-rule "pen_424b_max ( art424_basic ( defendant ?Defendant ) ) => ( max_imprisonment ( value 5 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_424b_max-deductive)
   (overruled-rule pen_424b_max-overruled)
   (system no)
   (support-rule pen_424b_max-support)
   (defeasibly-rule pen_424b_max-defeasibly)
   (defeated-rule nil))

([pen_424a_min] of defeasible-rule
   (rule-name pen_424a_min)
   (original-rule "pen_424a_min ( art424_acquittal ( defendant ?Defendant ) ) => ( min_imprisonment ( value 0 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_424a_min-deductive)
   (overruled-rule pen_424a_min-overruled)
   (system no)
   (support-rule pen_424a_min-support)
   (defeasibly-rule pen_424a_min-defeasibly)
   (defeated-rule nil))

([pen_424a_max] of defeasible-rule
   (rule-name pen_424a_max)
   (original-rule "pen_424a_max ( art424_acquittal ( defendant ?Defendant ) ) => ( max_imprisonment ( value 0 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_424a_max-deductive)
   (overruled-rule pen_424a_max-overruled)
   (system no)
   (support-rule pen_424a_max-support)
   (defeasibly-rule pen_424a_max-defeasibly)
   (defeated-rule nil))

