([art416_basic-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art416_basic)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule10_neg_416b-deductive-gen540] [rule8_neg_416b-deductive-gen534] [rule6_neg_416b-deductive-gen528] [rule4_neg_416b-deductive-gen522] [rule3_neg1-deductive-gen517] [rule2_neg-deductive-gen515] [rule1-deductive-gen513]))

([art416_qualified_gain-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art416_qualified_gain)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule10_neg_416qg-deductive-gen541] [rule8_neg_416qg-deductive-gen535] [rule6_neg_416qg-deductive-gen529] [rule4_neg_416qg-deductive-gen523] [rule3_neg2-deductive-gen518] [rule2-deductive-gen514]))

([art416_organized-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art416_organized)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule10_neg_416org-deductive-gen542] [rule8_neg_416org-deductive-gen536] [rule6_neg_416org-deductive-gen530] [rule4_neg_416org-deductive-gen524] [rule3-deductive-gen516]))

([art420_basic-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art420_basic)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule5_neg-deductive-gen521] [rule4-deductive-gen519]))

([art420_qualified-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art420_qualified)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule5-deductive-gen520]))

([art422_basic-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art422_basic)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7_neg-deductive-gen527] [rule6-deductive-gen525]))

([art422_organized-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art422_organized)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule7-deductive-gen526]))

([art423_basic-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art423_basic)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule9_neg-deductive-gen533] [rule8-deductive-gen531]))

([art423_qualified-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art423_qualified)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule9-deductive-gen532]))

([art424_basic-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art424_basic)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule11_neg-deductive-gen539] [rule10-deductive-gen537]))

([art424_acquittal-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label art424_acquittal)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule11-deductive-gen538]))

([min_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen_424a_min-deductive-gen563] [pen_424b_min-deductive-gen561] [pen_423q_min-deductive-gen559] [pen_423b_min-deductive-gen557] [pen_422org_min-deductive-gen555] [pen_422b_min-deductive-gen553] [pen_420q_min-deductive-gen551] [pen_420b_min-deductive-gen549] [pen_416org_min-deductive-gen547] [pen_416qg_min-deductive-gen545] [pen_416b_min-deductive-gen543]))

([max_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:name)
   (lc:defendant)
   (lc:abuse_of_authority)
   (lc:organized_group)
   (lc:high_gain)
   (lc:high_bribery)
   (lc:bribery_involved)
   (lc:previously_convicted)
   (lc:voluntary_disclosure)
   (lc:damage_to_public_interest)
   (lc:embezzlement)
   (lc:trading_influence)
   (lc:bribe_receiver)
   (lc:num_of_defendants)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen_424a_max-deductive-gen564] [pen_424b_max-deductive-gen562] [pen_423q_max-deductive-gen560] [pen_423b_max-deductive-gen558] [pen_422org_max-deductive-gen556] [pen_422b_max-deductive-gen554] [pen_420q_max-deductive-gen552] [pen_420b_max-deductive-gen550] [pen_416org_max-deductive-gen548] [pen_416qg_max-deductive-gen546] [pen_416b_max-deductive-gen544]))

